# -*- coding: UTF-8 -*-

from enum import Enum

# 资产负债表常量
class Debt(Enum):
    CurrencyMoney = '货币资金(元)'
    TransFinancial = '交易性金融资产(元)'
    ReceiveBill = '应收票据(元)'
    ReceiveCredit = '应收账款(元)'
    PaymentCredit = '预付账款(元)'
    ReceiveInterest = '应收利息(元)'
    ReceiveDivident = '应收股利(元)'
    ReceiveOtherCredit = '其他应收款(元)'
    Stock = '存货(元)'
    OneYearNoncurrentAssets = '一年内到期的非流动资产(元)'
    OtherFlowAsset = '其他流动资产(元)'
    FlowAssetCount = '流动资产合计(元)'
    SelledFinanceAsset = '可供出售金融资产(元)'
    LongReceiveCredit = '长期应收款(元)'
    LongStockInvest = '长期股权投资(元)'
    InvestProperty= '投资性房地产(元)'
    FixedAsset = '固定资产(元)'
    ProcessConstruction = '在建工程(元)'
    EngineeringMaterial = '工程物资(元)'
    IntangibleAssets = '无形资产(元)'
    Goodwill = '商誉(元)'
    LongtermUnamortizedExpenses = '长期待摊费用(元)'
    DeferredTaxAssets= '递延所得税资产(元)'
    TotalNoncurrentAssets = '非流动资产合计(元)'
    TotalAssets = '资产总计(元)'
    ShortTermBorrowing = '短期借款(元)'
    TradingFinancialLiabilities = '交易性金融负债(元)'
    NotesPayable = '应付票据(元)'
    AccountsPayable = '应付账款(元)'
    DepositReceived = '预收账款(元)'
    EmployeePayPayable = '应付职工薪酬(元)'
    TaxPayable = '应交税费(元)'
    AccrualInterestPayable = '应付利息(元)'
    DividendsPayable = '应付股利(元)'
    OtherPayables = '其他应付款(元)'
    OneYearNoncurrentLiability = '一年内到期的非流动负债(元)'
    OtherCurrentLiabilities = '其他流动负债(元)'
    TotalCurrentLiabilities = '流动负债合计(元)'
    LongTermLoan = '长期借款(元)'
    BondsPayable = '应付债券(元)'
    AccountPayableSpecialFunds = '专项应付款(元)'
    AnticipationLiabilities = '预计负债(元)'
    DeferredTaxLiabilities = '递延所得税负债(元)'
    OtherNoncurrentLiabilities = '其他非流动负债(元)'
    TotalNoncurrentLiabilities = '非流动负债合计(元)'
    TotalLiability = '负债合计(元)'
    CapitalStock = '股本(股)'
    CapitalReserve = '资本公积金(元)'
    TreasuryStock = '减:库存股(元)'
    SurplusAccumulationFund = '盈余公积金(元)'
    UndistributedProfit = '未分配利润(元)'
    TranslationReserve = '外币报表折算差额(元)'
    GenericRiskReserve = '一般风险准备(元)'
    ParentComTotalEquity= '归属于母公司股东权益合计(元)'
    MinorityEquity = '少数股东权益(元)'
    TotalShareHolderSequity = '股东权益合计(元)'
    TotalStockholderLiabilities= '负债和股东权益总计(元)'